package com.retroplay

import android.util.Log
import org.json.JSONArray
import org.json.JSONObject
import java.io.File
import java.util.zip.CRC32
import java.io.FileInputStream

/**
 * GamelistManager - Gestionnaire amélioré de gamelist.json
 * 
 * Génère et gère les fichiers gamelist.json avec métadonnées complètes.
 * Suit le format standard RetroArch/Libretro.
 * 
 * Format gamelist.json:
 * {
 *   "version": "1.0",
 *   "console": "nes",
 *   "games": [
 *     {
 *       "id": "1",
 *       "name": "Super Mario Bros",
 *       "path": "./Super Mario Bros.nes",
 *       "description": "...",
 *       "genre": "...",
 *       "releaseDate": "...",
 *       "players": "1-2",
 *       "crc32": "a1b2c3d4",
 *       "size": 40960,
 *       "serial": "...",
 *       "md5": "...",
 *       "sha1": "..."
 *     }
 *   ],
 *   "metadata": {
 *     "generatedAt": 1234567890,
 *     "sourceDirectories": ["/path/to/roms"],
 *     "autoGenerated": true
 *   }
 * }
 */
object GamelistManager {
    private const val TAG = "GamelistManager"
    private const val GAMELIST_VERSION = "1.0"
    
    /**
     * GameEntry - Format compatible RetroPie/EmulationStation (en JSON)
     * 
     * Champs de base (depuis BD lors de la génération):
     * - name, description, genre, releaseDate, players
     * 
     * Champs RetroPie (optionnels, depuis XML ou vides par défaut):
     * - rating, favorite, playcount, lastplayed
     * - image, thumbnail, video, marquee
     * 
     * Champs RetroPlay (supplémentaires):
     * - crc32, size, serial, md5, sha1
     * - corePath, coreName
     */
    data class GameEntry(
        // Champs de base (compatibles RetroPie)
        val id: String,
        val name: String,
        val path: String,
        val description: String? = null,
        val genre: String? = null,
        val releaseDate: String? = null,
        val players: String? = null,
        
        // Champs RetroPie (métadonnées enrichies depuis BD)
        val developer: String? = null,     // "Capcom", "Nintendo", etc.
        val publisher: String? = null,     // "Capcom", "Nintendo", etc.
        
        // Champs RetroPie (métadonnées personnalisées)
        val rating: String? = null,        // "0.85" (0.0-1.0)
        val favorite: String? = null,      // "true"/"false"
        val playcount: String? = null,     // "5"
        val lastplayed: String? = null,    // "2025-11-23T10:30:00"
        
        // Champs RetroPie (chemins médias)
        val image: String? = null,         // "./media/box2d/game.png"
        val thumbnail: String? = null,     // "./media/box2d/game.png"
        val video: String? = null,         // "./media/video/game.mp4"
        val marquee: String? = null,       // "./media/marquee/game.png"
        
        // Champs RetroPlay (supplémentaires)
        val crc32: String? = null,
        val size: Long? = null,
        val serial: String? = null,
        val md5: String? = null,
        val sha1: String? = null,
        val corePath: String? = null,
        val coreName: String? = null
    )
    
    data class GamelistMetadata(
        val generatedAt: Long,
        val sourceDirectories: List<String>,
        val autoGenerated: Boolean,
        val totalGames: Int,
        val console: String
    )
    
    data class Gamelist(
        val version: String,
        val console: String,
        val games: List<GameEntry>,
        val metadata: GamelistMetadata?
    )
    
    /**
     * Charge un gamelist.json existant
     */
    fun loadGamelist(consoleDir: File): Gamelist? {
        val gamelistFile = File(consoleDir, "gamelist.json")
        
        if (!gamelistFile.exists()) {
            Log.i(TAG, "gamelist.json not found for ${consoleDir.name}")
            return null
        }
        
        try {
            val jsonText = gamelistFile.readText()
            val jsonObj = JSONObject(jsonText)
            
            val version = jsonObj.optString("version", GAMELIST_VERSION)
            val console = jsonObj.optString("console", consoleDir.name)
            val gamesArray = jsonObj.getJSONArray("games")
            
            val games = mutableListOf<GameEntry>()
            for (i in 0 until gamesArray.length()) {
                try {
                    val gameObj = gamesArray.getJSONObject(i)
                    val game = parseGameEntry(gameObj)
                    if (game != null) {
                        games.add(game)
                    }
                } catch (e: Exception) {
                    Log.w(TAG, "Error parsing game at index $i: ${e.message}")
                }
            }
            
            // Parse metadata
            val metadataObj = jsonObj.optJSONObject("metadata")
            val metadata = if (metadataObj != null) {
                parseMetadata(metadataObj, console)
            } else {
                null
            }
            
            Log.i(TAG, "Loaded gamelist for ${consoleDir.name}: ${games.size} games")
            return Gamelist(version, console, games, metadata)
            
        } catch (e: Exception) {
            Log.e(TAG, "Error loading gamelist.json: ${e.message}", e)
            return null
        }
    }
    
    /**
     * Génère un gamelist.json automatiquement depuis les ROMs du répertoire
     */
    fun generateGamelist(
        consoleDir: File,
        consoleId: String,
        extensions: List<String> = getDefaultExtensions(consoleId),
        includeMetadata: Boolean = true
    ): Gamelist {
        // Normaliser l'ID de console pour obtenir les bonnes extensions
        val canonicalId = com.retroplay.ConsoleNameMapper.normalizeToCanonical(consoleId)
        val finalExtensions = if (extensions.isEmpty()) getDefaultExtensions(canonicalId) else extensions
        
        Log.i(TAG, "Generating gamelist for ${consoleDir.name} (consoleId: $consoleId, canonical: $canonicalId)")
        Log.d(TAG, "consoleDir.absolutePath: ${consoleDir.absolutePath}")
        Log.d(TAG, "consoleDir.exists(): ${consoleDir.exists()}")
        Log.d(TAG, "consoleDir.isDirectory: ${consoleDir.isDirectory}")
        Log.d(TAG, "Extensions utilisées: ${finalExtensions.joinToString(", ")}")
        
        val games = mutableListOf<GameEntry>()
        val sourceDirectories = mutableListOf<String>()
        
        // Scanner le répertoire principal
        sourceDirectories.add(consoleDir.absolutePath)
        scanDirectory(consoleDir, canonicalId, finalExtensions, games, consoleDir)
        
        Log.i(TAG, "ROMs trouvées avant tri: ${games.size}")
        
        // Trier par nom
        val sortedGames = games.sortedBy { it.name.lowercase() }
        
        // Assigner des IDs séquentiels
        val gamesWithIds = sortedGames.mapIndexed { index, game ->
            game.copy(id = (index + 1).toString())
        }
        
        Log.i(TAG, "Generated gamelist for ${consoleDir.name}: ${gamesWithIds.size} games")
        
        val metadata = if (includeMetadata) {
            GamelistMetadata(
                generatedAt = System.currentTimeMillis(),
                sourceDirectories = sourceDirectories,
                autoGenerated = true,
                totalGames = gamesWithIds.size,
                console = consoleId
            )
        } else {
            null
        }
        
        Log.i(TAG, "Generated gamelist for ${consoleDir.name}: ${gamesWithIds.size} games")
        return Gamelist(GAMELIST_VERSION, consoleId, gamesWithIds, metadata)
    }
    
    /**
     * Scanne un répertoire pour trouver des ROMs
     */
    private fun scanDirectory(
        dir: File,
        consoleId: String,
        extensions: List<String>,
        games: MutableList<GameEntry>,
        baseDir: File
    ) {
        if (!dir.exists() || !dir.isDirectory) {
            return
        }
        
        val files = dir.listFiles() ?: return
        
        for (file in files) {
            if (file.isDirectory) {
                // Scanner récursivement (pour sous-consoles comme fbneo/sega)
                scanDirectory(file, consoleId, extensions, games, baseDir)
            } else if (file.isFile) {
                val fileName = file.name.lowercase()
                val isValidRom = extensions.any { ext ->
                    fileName.endsWith(ext.lowercase())
                }
                
                if (isValidRom) {
                    Log.d(TAG, "ROM trouvée: ${file.name} (path: ${file.absolutePath}, exists: ${file.exists()})")
                    val game = createGameEntryFromFile(file, consoleId, baseDir)
                    if (game != null) {
                        games.add(game)
                    } else {
                        Log.w(TAG, "Failed to create GameEntry for ${file.name}")
                    }
                }
            }
        }
    }
    
    /**
     * Crée une entrée GameEntry à partir d'un fichier ROM
     */
    private fun createGameEntryFromFile(
        file: File,
        consoleId: String,
        baseDir: File
    ): GameEntry? {
        try {
            // IMPORTANT: Reconstruire le chemin correct à partir de baseDir et du nom du fichier
            // car file.absolutePath peut contenir un chemin incorrect (ex: /GameLibrary/ au lieu de /GameLibrary-Data/)
            val relativePath = try {
                file.relativeTo(baseDir).path.replace("\\", "/")
            } catch (e: IllegalArgumentException) {
                // Si file n'est pas un enfant de baseDir (chemins différents), calculer manuellement
                // Ex: file=/GameLibrary/... et baseDir=/GameLibrary-Data/...
                val filePath = try {
                    file.canonicalPath
                } catch (e2: Exception) {
                    file.absolutePath
                }
                val basePath = try {
                    baseDir.canonicalPath
                } catch (e2: Exception) {
                    baseDir.absolutePath
                }
                
                // Si les chemins sont différents, essayer de trouver le chemin relatif manuellement
                if (filePath.startsWith(basePath)) {
                    filePath.substring(basePath.length).trimStart('/').replace("\\", "/")
                } else {
                    // Fallback: utiliser juste le nom du fichier
                    file.name
                }
            }
            
            val correctFile = File(baseDir, relativePath)
            
            Log.d(TAG, "createGameEntryFromFile: file=${file.absolutePath}, baseDir=${baseDir.absolutePath}")
            Log.d(TAG, "  - file.canonicalPath: ${try { file.canonicalPath } catch (e: Exception) { "N/A" }}")
            Log.d(TAG, "  - relativePath: $relativePath")
            Log.d(TAG, "  - correctFile.absolutePath: ${correctFile.absolutePath}")
            Log.d(TAG, "  - correctFile.exists(): ${correctFile.exists()}")
            
            val fileName = file.name
            val baseName = fileName.substringBeforeLast(".")
            
            // Pour PSX, extraire le numéro de série au lieu de CRC32
            val serial = if (consoleId == "psx") {
                try {
                    PSXSerialExtractor.extractSerial(correctFile)
                } catch (e: Exception) {
                    Log.w(TAG, "Could not extract PSX serial for ${file.name}: ${e.message}")
                    null
                }
            } else {
                null
            }
            
            // CRC32 seulement si pas PSX (ou optionnel pour autres consoles)
            // Pour PSX, on utilise serial au lieu de CRC32
            val crc32 = if (consoleId != "psx") {
                try {
                    // Utiliser correctFile au lieu de file pour garantir le bon chemin
                    if (!correctFile.exists()) {
                        Log.w(TAG, "File does not exist for CRC32 calculation: ${correctFile.absolutePath}")
                        Log.w(TAG, "  - baseDir.absolutePath: ${baseDir.absolutePath}")
                        Log.w(TAG, "  - baseDir.exists(): ${baseDir.exists()}")
                        // Essayer avec le chemin canonique
                        try {
                            val canonicalFile = File(correctFile.canonicalPath)
                            if (canonicalFile.exists()) {
                                Log.i(TAG, "File exists at canonical path: ${canonicalFile.absolutePath}")
                                calculateCRC32(canonicalFile)
                            } else {
                                null
                            }
                        } catch (e: Exception) {
                            Log.w(TAG, "Could not get canonical path: ${e.message}")
                            null
                        }
                    } else {
                        calculateCRC32(correctFile)
                    }
                } catch (e: Exception) {
                    Log.w(TAG, "Could not calculate CRC32 for ${file.name} (path: ${correctFile.absolutePath}): ${e.message}")
                    null
                }
            } else {
                null  // Pas de CRC32 pour PSX, on utilise serial
            }
            
            // Enrichir avec la base de données pour TOUS les jeux (pas seulement arcade)
            // IMPORTANT: Passer consoleId directement à DatabaseManager.lookupGame()
            // qui fera la normalisation interne (normalizeConsoleForDatabase)
            // Cela permet de gérer correctement les sous-consoles comme fbneo/cps1, dataeast, taito, etc.
            val normalizedConsoleId = com.retroplay.ConsoleNameMapper.normalizeToCanonical(consoleId)
            val isArcade = normalizedConsoleId == "arcade" || normalizedConsoleId == "mame" || 
                          normalizedConsoleId == "fbneo" || consoleId.startsWith("fbneo") || 
                          consoleId.startsWith("mame") || 
                          // Toutes les sous-consoles arcade directes
                          consoleId == "cps1" || consoleId == "cps2" || consoleId == "cps3" ||
                          consoleId == "cpiii" || consoleId == "dataeast" || consoleId == "taito" ||
                          consoleId == "neogeo" || consoleId == "sega"
            
            var gameName = baseName
            var gameDescription: String? = null
            var gameGenre: String? = null
            var gameReleaseDate: String? = null
            var gamePlayers: String? = null
            var gameDeveloper: String? = null
            var gamePublisher: String? = null
            
            // Pour TOUS les jeux avec CRC32, chercher dans la base de données
            // TOUT doit être enrichi lors de la génération initiale
            if (crc32 != null) {
                try {
                    // IMPORTANT: Passer consoleId directement (pas normalizedConsoleId)
                    // DatabaseManager.lookupGame() fera la normalisation interne
                    // Cela permet de gérer correctement les sous-consoles comme fbneo/cps1, dataeast, taito, etc.
                    val gameInfo = com.retroplay.database.DatabaseManager.lookupGame(crc32, consoleId)
                    if (gameInfo != null) {
                        // Nom: toujours utiliser pour arcade, sinon seulement si vide
                        if (gameInfo.name.isNotEmpty()) {
                            if (isArcade) {
                                // Pour arcade: toujours remplacer (set names courts -> vrais titres)
                                gameName = gameInfo.name
                                Log.d(TAG, "Found arcade game name from database: $gameName (CRC: $crc32)")
                            } else {
                                // Pour autres consoles: utiliser seulement si le nom actuel est vide ou basique
                                if (gameName.isEmpty() || gameName == baseName) {
                                    gameName = gameInfo.name
                                    Log.d(TAG, "Found game name from database: $gameName (CRC: $crc32)")
                                }
                            }
                        }
                        
                        // Enrichir TOUTES les métadonnées depuis la base de données
                        gameInfo.genre?.let { gameGenre = it }
                        gameInfo.developer?.let { gameDeveloper = it }
                        gameInfo.publisher?.let { gamePublisher = it }
                        
                        // Description: construire à partir de developer/publisher si disponibles
                        if (gameDeveloper != null) {
                            if (gamePublisher != null && gamePublisher != gameDeveloper) {
                                gameDescription = "Developer: $gameDeveloper | Publisher: $gamePublisher"
                            } else {
                                gameDescription = "Developer: $gameDeveloper"
                            }
                        }
                        
                        gameInfo.releaseYear?.let { year ->
                            gameInfo.releaseMonth?.let { month ->
                                gameReleaseDate = String.format("%04d-%02d", year, month)
                            } ?: run {
                                gameReleaseDate = year.toString()
                            }
                        }
                        if (gameInfo.maxPlayers > 1) {
                            gamePlayers = "1-${gameInfo.maxPlayers}"
                        } else if (gameInfo.maxPlayers == 1) {
                            gamePlayers = "1"
                        }
                        
                        Log.d(TAG, "✅ Enriched game metadata from database: $gameName (Genre: $gameGenre, Developer: $gameDeveloper, Publisher: $gamePublisher, Year: $gameReleaseDate, Players: $gamePlayers)")
                    } else {
                        // Fallback: nettoyer le nom du fichier seulement pour arcade
                        if (isArcade) {
                            gameName = baseName.replace("_", " ")
                                .split(" ")
                                .joinToString(" ") { word ->
                                    if (word.isEmpty()) ""
                                    else word[0].uppercaseChar() + word.substring(1).lowercase()
                                }
                            Log.d(TAG, "Arcade game not found in database, using cleaned filename: $gameName")
                        }
                    }
                } catch (e: Exception) {
                    Log.w(TAG, "Error looking up game in database: ${e.message}, using filename")
                    // Fallback sur le nom nettoyé seulement pour arcade
                    if (isArcade) {
                        gameName = baseName.replace("_", " ")
                            .split(" ")
                            .joinToString(" ") { word ->
                                if (word.isEmpty()) ""
                                else word[0].uppercaseChar() + word.substring(1).lowercase()
                            }
                    }
                }
            }
            
            // Taille du fichier (utiliser correctFile pour garantir le bon chemin)
            val size = correctFile.length()
            
            // Générer les chemins médias par défaut (compatibles RetroPie)
            val baseNameForMedia = gameName
            val defaultImage = "./media/box2d/$baseNameForMedia.png"
            val defaultThumbnail = "./media/box2d/$baseNameForMedia.png"
            
            return GameEntry(
                id = "0", // Sera assigné plus tard
                name = gameName,
                path = "./$relativePath",
                description = gameDescription,
                genre = gameGenre,
                releaseDate = gameReleaseDate,
                players = gamePlayers,
                
                // Champs RetroPie (enrichis depuis BD lors de la génération)
                developer = gameDeveloper,
                publisher = gamePublisher,
                
                // Champs RetroPie (vides par défaut, seront enrichis par XML si disponible)
                rating = null,
                favorite = null,
                playcount = null,
                lastplayed = null,
                
                // Champs RetroPie (chemins médias par défaut)
                image = defaultImage,
                thumbnail = defaultThumbnail,
                video = null,  // Pas de vidéo par défaut
                marquee = null, // Pas de marquee par défaut
                
                // Champs RetroPlay (supplémentaires)
                crc32 = crc32,
                size = size,
                serial = serial,
                md5 = null,
                sha1 = null,
                corePath = null,
                coreName = null
            )
            
        } catch (e: Exception) {
            Log.e(TAG, "Error creating game entry from ${file.name}: ${e.message}", e)
            return null
        }
    }
    
    /**
     * Calcule le CRC32 d'un fichier
     */
    private fun calculateCRC32(file: File): String? {
        try {
            Log.d(TAG, "calculateCRC32: file=${file.absolutePath}, exists=${file.exists()}, canRead=${file.canRead()}, length=${file.length()}")
            
            if (!file.exists()) {
                Log.e(TAG, "File does not exist for CRC32: ${file.absolutePath}")
                return null
            }
            
            if (!file.canRead()) {
                Log.e(TAG, "File cannot be read for CRC32: ${file.absolutePath}")
                return null
            }
            
            val crc32 = CRC32()
            FileInputStream(file).use { input ->
                val buffer = ByteArray(8192)
                var bytesRead: Int
                while (input.read(buffer).also { bytesRead = it } != -1) {
                    crc32.update(buffer, 0, bytesRead)
                }
            }
            val crcValue = String.format("%08x", crc32.value)
            Log.d(TAG, "CRC32 calculated successfully: $crcValue for ${file.name}")
            return crcValue
        } catch (e: Exception) {
            Log.e(TAG, "Error calculating CRC32 for ${file.absolutePath}: ${e.javaClass.simpleName} - ${e.message}", e)
            return null
        }
    }
    
    /**
     * Sauvegarde un gamelist.json
     */
    fun saveGamelist(gamelist: Gamelist, consoleDir: File): Boolean {
        try {
            val gamelistFile = File(consoleDir, "gamelist.json")
            
            val jsonObj = JSONObject().apply {
                put("version", gamelist.version)
                put("console", gamelist.console)
                
                val gamesArray = JSONArray()
                gamelist.games.forEach { game ->
                    gamesArray.put(gameToJson(game))
                }
                put("games", gamesArray)
                
                if (gamelist.metadata != null) {
                    put("metadata", metadataToJson(gamelist.metadata))
                }
            }
            
            gamelistFile.writeText(jsonObj.toString(2)) // Indentation pour lisibilité
            Log.i(TAG, "Saved gamelist.json for ${consoleDir.name}: ${gamelist.games.size} games")
            return true
            
        } catch (e: Exception) {
            Log.e(TAG, "Error saving gamelist.json: ${e.message}", e)
            return false
        }
    }
    
    /**
     * Convertit un GameEntry en JSONObject
     * Format compatible RetroPie/EmulationStation (en JSON)
     */
    private fun gameToJson(game: GameEntry): JSONObject {
        return JSONObject().apply {
            // Champs de base (compatibles RetroPie)
            put("id", game.id)
            put("name", game.name)
            put("path", game.path)
            
            // Métadonnées de base (depuis BD)
            if (game.description != null && game.description.isNotEmpty()) {
                put("description", game.description)
            }
            if (game.genre != null && game.genre.isNotEmpty()) {
                put("genre", game.genre)
            }
            if (game.releaseDate != null && game.releaseDate.isNotEmpty()) {
                put("releaseDate", game.releaseDate)
            }
            if (game.players != null && game.players.isNotEmpty()) {
                put("players", game.players)
            }
            
            // Champs RetroPie (enrichis depuis BD)
            if (game.developer != null && game.developer.isNotEmpty()) {
                put("developer", game.developer)
            }
            if (game.publisher != null && game.publisher.isNotEmpty()) {
                put("publisher", game.publisher)
            }
            
            // Champs RetroPie (métadonnées personnalisées)
            if (game.rating != null && game.rating.isNotEmpty()) {
                put("rating", game.rating)
            }
            if (game.favorite != null && game.favorite.isNotEmpty()) {
                put("favorite", game.favorite)
            }
            if (game.playcount != null && game.playcount.isNotEmpty()) {
                put("playcount", game.playcount)
            }
            if (game.lastplayed != null && game.lastplayed.isNotEmpty()) {
                put("lastplayed", game.lastplayed)
            }
            
            // Champs RetroPie (chemins médias)
            if (game.image != null && game.image.isNotEmpty()) {
                put("image", game.image)
            }
            if (game.thumbnail != null && game.thumbnail.isNotEmpty()) {
                put("thumbnail", game.thumbnail)
            }
            if (game.video != null && game.video.isNotEmpty()) {
                put("video", game.video)
            }
            if (game.marquee != null && game.marquee.isNotEmpty()) {
                put("marquee", game.marquee)
            }
            
            // Champs RetroPlay (supplémentaires)
            if (game.crc32 != null) put("crc32", game.crc32)
            if (game.size != null) put("size", game.size)
            if (game.serial != null) put("serial", game.serial)
            if (game.md5 != null) put("md5", game.md5)
            if (game.sha1 != null) put("sha1", game.sha1)
            
            // Configuration core
            if (game.corePath != null) put("core_path", game.corePath)
            if (game.coreName != null) put("core_name", game.coreName)
        }
    }
    
    /**
     * Convertit un GamelistMetadata en JSONObject
     */
    private fun metadataToJson(metadata: GamelistMetadata): JSONObject {
        return JSONObject().apply {
            put("generatedAt", metadata.generatedAt)
            put("sourceDirectories", JSONArray(metadata.sourceDirectories))
            put("autoGenerated", metadata.autoGenerated)
            put("totalGames", metadata.totalGames)
            put("console", metadata.console)
        }
    }
    
    /**
     * Parse un GameEntry depuis JSONObject
     * Support des formats legacy et nouveau (compatible RetroPie)
     */
    private fun parseGameEntry(obj: JSONObject): GameEntry? {
        try {
            // Support des deux formats : "description"/"releaseDate" (nouveau) et "desc"/"releasedate" (legacy)
            val description = if (obj.has("description")) obj.optString("description", "") else obj.optString("desc", "")
            val descriptionValue = if (description.isNotEmpty()) description else null
            val releaseDate = if (obj.has("releaseDate")) obj.optString("releaseDate", "") else obj.optString("releasedate", "")
            val releaseDateValue = if (releaseDate.isNotEmpty()) releaseDate else null
            
            // Helper pour lire une string optionnelle
            fun optStringOrNull(key: String): String? {
                return if (obj.has(key)) {
                    val value = obj.optString(key, "")
                    if (value.isNotEmpty()) value else null
                } else null
            }
            
            return GameEntry(
                // Champs de base
                id = obj.getString("id"),
                name = obj.getString("name"),
                path = obj.getString("path"),
                description = descriptionValue,
                genre = optStringOrNull("genre"),
                releaseDate = releaseDateValue,
                players = optStringOrNull("players"),
                
                // Champs RetroPie (enrichis depuis BD)
                developer = optStringOrNull("developer"),
                publisher = optStringOrNull("publisher"),
                
                // Champs RetroPie (métadonnées personnalisées)
                rating = optStringOrNull("rating"),
                favorite = optStringOrNull("favorite"),
                playcount = optStringOrNull("playcount"),
                lastplayed = optStringOrNull("lastplayed"),
                
                // Champs RetroPie (chemins médias)
                image = optStringOrNull("image"),
                thumbnail = optStringOrNull("thumbnail"),
                video = optStringOrNull("video"),
                marquee = optStringOrNull("marquee"),
                
                // Champs RetroPlay (supplémentaires)
                crc32 = optStringOrNull("crc32"),
                size = if (obj.has("size")) obj.getLong("size") else null,
                serial = optStringOrNull("serial"),
                md5 = optStringOrNull("md5"),
                sha1 = optStringOrNull("sha1"),
                corePath = optStringOrNull("core_path"),
                coreName = optStringOrNull("core_name")
            )
        } catch (e: Exception) {
            Log.e(TAG, "Error parsing game entry: ${e.message}", e)
            return null
        }
    }
    
    /**
     * Parse un GamelistMetadata depuis JSONObject
     */
    private fun parseMetadata(obj: JSONObject, console: String): GamelistMetadata {
        val sourceDirs = mutableListOf<String>()
        val dirsArray = obj.optJSONArray("sourceDirectories")
        if (dirsArray != null) {
            for (i in 0 until dirsArray.length()) {
                sourceDirs.add(dirsArray.getString(i))
            }
        }
        
        return GamelistMetadata(
            generatedAt = obj.optLong("generatedAt", System.currentTimeMillis()),
            sourceDirectories = sourceDirs,
            autoGenerated = obj.optBoolean("autoGenerated", false),
            totalGames = obj.optInt("totalGames", 0),
            console = obj.optString("console", console)
        )
    }
    
    /**
     * Obtient les extensions par défaut pour une console
     * Utilise ConsoleNameMapper pour normaliser les noms alternatifs
     */
    fun getDefaultExtensions(consoleId: String): List<String> {
        // Normaliser avec ConsoleNameMapper (depuis Java)
        val canonicalId = com.retroplay.ConsoleNameMapper.normalizeToCanonical(consoleId)
        
        return when (canonicalId) {
            "nes" -> listOf(".nes", ".fds", ".unf", ".zip")
            "snes" -> listOf(".smc", ".sfc", ".fig", ".zip")
            "n64" -> listOf(".n64", ".z64", ".v64", ".zip")
            "gb" -> listOf(".gb", ".zip")
            "gbc" -> listOf(".gbc", ".zip")
            "gba" -> listOf(".gba", ".agb", ".zip")
            "genesis" -> listOf(".md", ".gen", ".smd", ".32x", ".zip")
            "megadrive" -> listOf(".md", ".gen", ".smd", ".32x", ".zip") // Alias pour genesis
            "mastersystem" -> listOf(".sms", ".zip")
            "gamegear" -> listOf(".gg", ".zip")
            "segacd" -> listOf(".iso", ".cue", ".bin", ".img", ".chd", ".gdi", ".zip")
            "psx" -> listOf(".iso", ".cue", ".bin", ".img", ".mdf", ".pbp", ".zip")
            "psp" -> listOf(".iso", ".cso", ".pbp", ".elf", ".zip")
            "atari2600" -> listOf(".a26", ".bin", ".zip")
            "atari5200" -> listOf(".a52", ".bin", ".zip")
            "atari7800" -> listOf(".a78", ".bin", ".zip", ".7z")
            "lynx" -> listOf(".lnx", ".zip")
            "ngp" -> listOf(".ngp", ".ngc", ".zip")
            "wonderswancolor" -> listOf(".ws", ".wsc", ".zip")
            "pce" -> listOf(".pce", ".sgx", ".zip")
            "fbneo" -> listOf(".zip", ".7z")
            "arcade" -> listOf(".zip", ".7z")
            "c64" -> listOf(".d64", ".d71", ".d81", ".t64", ".tap", ".prg", ".crt", ".bin", ".zip")
            "amiga" -> listOf(".adf", ".dsk", ".ipf", ".zip")
            "zxspectrum" -> listOf(".tap", ".tzx", ".z80", ".sna", ".dsk", ".trd", ".scl", ".zip")
            "spectrum" -> listOf(".tap", ".tzx", ".z80", ".sna", ".dsk", ".trd", ".scl", ".zip") // Alias
            else -> listOf(".zip", ".7z", ".rom", ".bin")
        }
    }
    
    /**
     * Fusionne deux gamelists (utile pour multi-répertoires)
     */
    fun mergeGamelists(gamelist1: Gamelist, gamelist2: Gamelist): Gamelist {
        val mergedGames = (gamelist1.games + gamelist2.games).distinctBy { it.path }
            .sortedBy { it.name.lowercase() }
        
        // Réassigner les IDs
        val reassignedGames = mergedGames.mapIndexed { index, game ->
            game.copy(id = (index + 1).toString())
        }
        
        val mergedMetadata = if (gamelist1.metadata != null && gamelist2.metadata != null) {
            GamelistMetadata(
                generatedAt = maxOf(gamelist1.metadata.generatedAt, gamelist2.metadata.generatedAt),
                sourceDirectories = (gamelist1.metadata.sourceDirectories + gamelist2.metadata.sourceDirectories).distinct(),
                autoGenerated = gamelist1.metadata.autoGenerated || gamelist2.metadata.autoGenerated,
                totalGames = reassignedGames.size,
                console = gamelist1.console
            )
        } else {
            null
        }
        
        return Gamelist(
            version = GAMELIST_VERSION,
            console = gamelist1.console,
            games = reassignedGames,
            metadata = mergedMetadata
        )
    }
    
    /**
     * Génère un gamelist.json au format JSON string (pour utilisation depuis Java)
     * Version simplifiée pour WebServer.java
     */
    @JvmStatic
    fun generateGamelistJsonString(consoleDir: File, consoleId: String): String {
        try {
            val gamelist = generateGamelist(consoleDir, consoleId)
            val jsonObj = org.json.JSONObject().apply {
                put("version", gamelist.version)
                put("console", gamelist.console)
                
                val gamesArray = org.json.JSONArray()
                gamelist.games.forEach { game ->
                    val gameObj = org.json.JSONObject().apply {
                        put("id", game.id)
                        put("name", game.name)
                        put("path", game.path)
                        
                        // NOUVEAU FORMAT (camelCase) - Format standard
                        put("description", game.description ?: "")
                        put("genre", game.genre ?: "")
                        put("releaseDate", game.releaseDate ?: "")
                        put("players", game.players ?: "")
                        
                        // Champs RetroPie (enrichis depuis BD)
                        if (game.developer != null && game.developer.isNotEmpty()) {
                            put("developer", game.developer)
                        }
                        if (game.publisher != null && game.publisher.isNotEmpty()) {
                            put("publisher", game.publisher)
                        }
                        
                        // Métadonnées techniques
                        if (game.crc32 != null) put("crc32", game.crc32)
                        if (game.size != null) put("size", game.size)
                        if (game.serial != null) put("serial", game.serial)
                        if (game.md5 != null) put("md5", game.md5)
                        if (game.sha1 != null) put("sha1", game.sha1)
                        
                        // Configuration core
                        if (game.corePath != null) put("core_path", game.corePath)
                        if (game.coreName != null) put("core_name", game.coreName)
                        
                        // Chemins d'images (compatibilité avec format existant)
                        val baseName = game.name
                        put("image", "./media/box2d/$baseName.png")
                        put("screenshot", "./media/screenshot/$baseName.png")
                        put("thumbnail", "./media/box2d/$baseName.png")
                    }
                    gamesArray.put(gameObj)
                }
                put("games", gamesArray)
                
                // Ajouter metadata si disponible
                if (gamelist.metadata != null) {
                    val metadata = gamelist.metadata
                    val metadataObj = org.json.JSONObject().apply {
                        put("generatedAt", metadata.generatedAt)
                        put("autoGenerated", metadata.autoGenerated)
                        put("totalGames", metadata.totalGames)
                        put("console", metadata.console)
                        
                        val sourceDirsArray = org.json.JSONArray()
                        metadata.sourceDirectories.forEach { sourceDirsArray.put(it) }
                        put("sourceDirectories", sourceDirsArray)
                    }
                    put("metadata", metadataObj)
                }
            }
            
            return jsonObj.toString(2) // Indentation pour lisibilité
            
        } catch (e: Exception) {
            Log.e(TAG, "Error generating gamelist JSON string: ${e.message}", e)
            return "{\"games\":[]}" // Fallback
        }
    }
}

