package com.retroplay

import android.util.Log
import kotlinx.coroutines.*
import org.json.JSONArray
import org.json.JSONObject
import java.io.File

/**
 * GamelistManager - Gestionnaire amélioré de gamelist.json
 * 
 * Génère et gère les fichiers gamelist.json avec métadonnées complètes.
 * Suit le format standard RetroArch/Libretro.
 * 
 * Format gamelist.json:
 * {
 *   "version": "1.0",
 *   "console": "nes",
 *   "games": [
 *     {
 *       "id": "1",
 *       "name": "Super Mario Bros",
 *       "path": "./Super Mario Bros.nes",
 *       "description": "...",
 *       "genre": "...",
 *       "releaseDate": "...",
 *       "players": "1-2",
 *       "crc32": "a1b2c3d4",
 *       "size": 40960,
 *       "serial": "...",
 *       "md5": "...",
 *       "sha1": "..."
 *     }
 *   ],
 *   "metadata": {
 *     "generatedAt": 1234567890,
 *     "sourceDirectories": ["/path/to/roms"],
 *     "autoGenerated": true
 *   }
 * }
 */
object GamelistManager {
    private const val TAG = "GamelistManager"
    private const val GAMELIST_VERSION = "1.0"
    
    /**
     * GameEntry - Structure ES (EmulationStation) style
     * Compatible avec format gamelist.json standard
     */
    data class GameEntry(
        val id: String,
        val name: String,
        val path: String,              // Chemin relatif (ex: "./mario.nes")
        val desc: String? = null,      // Description complète
        val image: String? = null,     // Chemin image boxart
        val releasedate: String? = null, // Format: YYYYMMDDTHHMMSS (ES style)
        val developer: String? = null,
        val publisher: String? = null,
        val genre: String? = null,
        val players: String? = null,  // Format: "1-2" ou "1"
        val hash: String? = null,     // Hash principal (SHA1, MD5 ou CRC32)
        val rating: String? = null     // Note (optionnel)
    )
    
    data class GamelistMetadata(
        val generatedAt: Long,
        val sourceDirectories: List<String>,
        val autoGenerated: Boolean,
        val totalGames: Int,
        val console: String
    )
    
    data class Gamelist(
        val version: String,
        val console: String,
        val games: List<GameEntry>,
        val metadata: GamelistMetadata?
    )
    
    /**
     * Charge un gamelist.json existant
     */
    fun loadGamelist(consoleDir: File): Gamelist? {
        val gamelistFile = File(consoleDir, "gamelist.json")
        
        if (!gamelistFile.exists()) {
            Log.i(TAG, "gamelist.json not found for ${consoleDir.name}")
            return null
        }
        
        try {
            val jsonText = gamelistFile.readText()
            val jsonObj = JSONObject(jsonText)
            
            val version = jsonObj.optString("version", GAMELIST_VERSION)
            val console = jsonObj.optString("console", consoleDir.name)
            
            // Vérifier si "games" existe pour éviter les plantages
            val gamesArray = if (jsonObj.has("games") && !jsonObj.isNull("games")) {
                jsonObj.getJSONArray("games")
            } else {
                Log.w(TAG, "No 'games' array found in gamelist.json for ${consoleDir.name}")
                JSONArray() // Retourner un tableau vide
            }
            
            val games = mutableListOf<GameEntry>()
            for (i in 0 until gamesArray.length()) {
                try {
                    val gameObj = gamesArray.getJSONObject(i)
                    val game = parseGameEntry(gameObj)
                    if (game != null) {
                        games.add(game)
                    }
                } catch (e: Exception) {
                    Log.w(TAG, "Error parsing game at index $i: ${e.message}")
                }
            }
            
            // Parse metadata
            val metadataObj = jsonObj.optJSONObject("metadata")
            val metadata = if (metadataObj != null) {
                parseMetadata(metadataObj, console)
            } else {
                null
            }
            
            Log.i(TAG, "Loaded gamelist for ${consoleDir.name}: ${games.size} games")
            return Gamelist(version, console, games, metadata)
            
        } catch (e: Exception) {
            Log.e(TAG, "Error loading gamelist.json: ${e.message}", e)
            return null
        }
    }
    
    /**
     * Génère un gamelist.json automatiquement depuis les ROMs du répertoire
     */
    fun generateGamelist(
        consoleDir: File,
        consoleId: String,
        extensions: List<String> = getDefaultExtensions(consoleId),
        includeMetadata: Boolean = true
    ): Gamelist {
        // Normaliser l'ID de console pour obtenir les bonnes extensions
        val canonicalId = com.retroplay.ConsoleNameMapper.normalizeToCanonical(consoleId)
        val finalExtensions = if (extensions.isEmpty()) getDefaultExtensions(canonicalId) else extensions
        
        Log.i(TAG, "Generating gamelist for ${consoleDir.name} (consoleId: $consoleId, canonical: $canonicalId)")
        Log.d(TAG, "Extensions utilisées: ${finalExtensions.joinToString(", ")}")
        
        val games = mutableListOf<GameEntry>()
        val sourceDirectories = mutableListOf<String>()
        
        // Scanner le répertoire principal
        sourceDirectories.add(consoleDir.absolutePath)
        scanDirectory(consoleDir, canonicalId, finalExtensions, games, consoleDir)
        
        Log.i(TAG, "ROMs trouvées avant tri: ${games.size}")
        
        // Trier par nom
        val sortedGames = games.sortedBy { it.name.lowercase() }
        
        // Assigner des IDs séquentiels
        val gamesWithIds = sortedGames.mapIndexed { index, game ->
            game.copy(id = (index + 1).toString())
        }
        
        Log.i(TAG, "Generated gamelist for ${consoleDir.name}: ${gamesWithIds.size} games")
        
        val metadata = if (includeMetadata) {
            GamelistMetadata(
                generatedAt = System.currentTimeMillis(),
                sourceDirectories = sourceDirectories,
                autoGenerated = true,
                totalGames = gamesWithIds.size,
                console = consoleId
            )
        } else {
            null
        }
        
        Log.i(TAG, "Generated gamelist for ${consoleDir.name}: ${gamesWithIds.size} games")
        return Gamelist(GAMELIST_VERSION, consoleId, gamesWithIds, metadata)
    }
    
    /**
     * Scanne un répertoire pour trouver des ROMs
     */
    private fun scanDirectory(
        dir: File,
        consoleId: String,
        extensions: List<String>,
        games: MutableList<GameEntry>,
        baseDir: File
    ) {
        if (!dir.exists() || !dir.isDirectory) {
            return
        }
        
        val files = dir.listFiles() ?: return
        
        for (file in files) {
            if (file.isDirectory) {
                // Scanner récursivement (pour sous-consoles comme fbneo/sega)
                scanDirectory(file, consoleId, extensions, games, baseDir)
            } else if (file.isFile) {
                val fileName = file.name.lowercase()
                val isValidRom = extensions.any { ext ->
                    fileName.endsWith(ext.lowercase())
                }
                
                if (isValidRom) {
                    val game = createGameEntryFromFile(file, consoleId, baseDir)
                    if (game != null) {
                        games.add(game)
                        Log.d(TAG, "ROM trouvée: ${file.name}")
                    }
                }
            }
        }
    }
    
    /**
     * Scanne un répertoire pour trouver de NOUVELLES ROMs seulement (optimisé pour addNewRomsToGamelist)
     * Vérifie d'abord si le fichier existe déjà avant de calculer le hash
     */
    private fun scanDirectoryForNewRoms(
        dir: File,
        consoleId: String,
        extensions: List<String>,
        games: MutableList<GameEntry>,
        baseDir: File,
        existingPaths: Set<String>
    ) {
        if (!dir.exists() || !dir.isDirectory) {
            return
        }
        
        val files = dir.listFiles() ?: return
        
        for (file in files) {
            if (file.isDirectory) {
                // Scanner récursivement (pour sous-consoles comme fbneo/sega)
                scanDirectoryForNewRoms(file, consoleId, extensions, games, baseDir, existingPaths)
            } else if (file.isFile) {
                val fileName = file.name.lowercase()
                val isValidRom = extensions.any { ext ->
                    fileName.endsWith(ext.lowercase())
                }
                
                if (isValidRom) {
                    // Vérifier d'abord si le fichier existe déjà (sans calculer le hash)
                    val relativePath = file.relativeTo(baseDir).path.replace("\\", "/")
                    val normalizedPath = if (relativePath.startsWith("./")) relativePath.substring(2) else relativePath
                    
                    // Si le fichier existe déjà, skip (pas besoin de calculer le hash)
                    if (existingPaths.contains(normalizedPath)) {
                        continue // Skip ce fichier, il existe déjà
                    }
                    
                    // C'est une nouvelle ROM, créer l'entrée basique (sans hash)
                    val game = createGameEntryFromFile(file, consoleId, baseDir)
                    if (game != null) {
                        games.add(game)
                        Log.d(TAG, "Nouvelle ROM trouvée: ${file.name}")
                    }
                }
            }
        }
    }
    
    /**
     * Crée une entrée GameEntry basique à partir d'un fichier ROM
     * Pas de hash, pas de métadonnées - juste name et path
     * L'utilisateur gère les métadonnées manuellement sur PC
     */
    private fun createGameEntryFromFile(
        file: File,
        consoleId: String,
        baseDir: File
    ): GameEntry? {
        try {
            val fileName = file.name
            val baseName = fileName.substringBeforeLast(".")
            val relativePath = file.relativeTo(baseDir).path.replace("\\", "/")
            
            // Créer entrée basique sans hash ni métadonnées
            return createBasicGameEntry(baseName, relativePath)
            
        } catch (e: Exception) {
            Log.e(TAG, "Error creating game entry from ${file.name}: ${e.message}", e)
            return null
        }
    }
    
    /**
     * Nettoie le nom de fichier pour en faire un nom de jeu lisible
     */
    private fun cleanFileName(fileName: String): String {
        return fileName.replace("_", " ")
            .split(" ")
            .joinToString(" ") { word ->
                if (word.isEmpty()) ""
                else word[0].uppercaseChar() + word.substring(1).lowercase()
            }
    }
    
    /**
     * Crée une entrée basique sans métadonnées (fallback)
     */
    private fun createBasicGameEntry(baseName: String, relativePath: String): GameEntry {
        val gameName = cleanFileName(baseName)
        return GameEntry(
            id = "0",
            name = gameName,
            path = "./$relativePath",
            desc = "",
            image = "./media/box2d/$gameName.png",
            releasedate = "",
            developer = "",
            publisher = "",
            genre = "",
            players = "",
            hash = "",
            rating = ""
        )
    }
    
    
    /**
     * Sauvegarde un gamelist.json
     */
    fun saveGamelist(gamelist: Gamelist, consoleDir: File): Boolean {
        try {
            val gamelistFile = File(consoleDir, "gamelist.json")
            
            val jsonObj = JSONObject().apply {
                put("version", gamelist.version)
                put("console", gamelist.console)
                
                val gamesArray = JSONArray()
                gamelist.games.forEach { game ->
                    gamesArray.put(gameToJson(game))
                }
                put("games", gamesArray)
                
                if (gamelist.metadata != null) {
                    put("metadata", metadataToJson(gamelist.metadata))
                }
            }
            
            gamelistFile.writeText(jsonObj.toString(2)) // Indentation pour lisibilité
            Log.i(TAG, "Saved gamelist.json for ${consoleDir.name}: ${gamelist.games.size} games")
            return true
            
        } catch (e: Exception) {
            Log.e(TAG, "Error saving gamelist.json: ${e.message}", e)
            return false
        }
    }
    
    /**
     * Convertit un GameEntry en JSONObject
     * Format standardisé: description, releaseDate (camelCase)
     * Compatible avec parsing qui supporte les deux formats (legacy et nouveau)
     */
    /**
     * Convertit un GameEntry en JSONObject (format ES)
     */
    private fun gameToJson(game: GameEntry): JSONObject {
        return JSONObject().apply {
            put("id", game.id)
            put("name", game.name)
            put("path", game.path)
            
            // Format ES (EmulationStation style)
            // Toujours inclure les champs, même s'ils sont vides (chaînes vides au lieu de null)
            put("desc", game.desc ?: "")
            put("image", game.image ?: "")
            put("releasedate", game.releasedate ?: "")
            put("developer", game.developer ?: "")
            put("publisher", game.publisher ?: "")
            put("genre", game.genre ?: "")
            put("players", game.players ?: "")
            put("hash", game.hash ?: "")
            put("rating", game.rating ?: "")
        }
    }
    
    /**
     * Convertit un GamelistMetadata en JSONObject
     */
    private fun metadataToJson(metadata: GamelistMetadata): JSONObject {
        return JSONObject().apply {
            put("generatedAt", metadata.generatedAt)
            put("sourceDirectories", JSONArray(metadata.sourceDirectories))
            put("autoGenerated", metadata.autoGenerated)
            put("totalGames", metadata.totalGames)
            put("console", metadata.console)
        }
    }
    
    /**
     * Parse un GameEntry depuis JSONObject (format ES)
     * Support legacy pour compatibilité
     */
    private fun parseGameEntry(obj: JSONObject): GameEntry? {
        try {
            // Support legacy: "description"/"releaseDate" (ancien format)
            // Format ES: "desc"/"releasedate" (nouveau format)
            // Retourner des chaînes vides au lieu de null
            val desc = when {
                obj.has("desc") && !obj.isNull("desc") -> obj.getString("desc")
                obj.has("description") && !obj.isNull("description") -> obj.getString("description")
                else -> ""
            }
            val releasedate = when {
                obj.has("releasedate") && !obj.isNull("releasedate") -> obj.getString("releasedate")
                obj.has("releaseDate") && !obj.isNull("releaseDate") -> obj.getString("releaseDate")
                else -> ""
            }
            
            // Vérifier les champs obligatoires pour éviter les plantages
            if (!obj.has("id") || obj.isNull("id")) {
                Log.w(TAG, "Game entry missing 'id' field, skipping")
                return null
            }
            if (!obj.has("name") || obj.isNull("name")) {
                Log.w(TAG, "Game entry missing 'name' field, skipping")
                return null
            }
            if (!obj.has("path") || obj.isNull("path")) {
                Log.w(TAG, "Game entry missing 'path' field, skipping")
                return null
            }
            
            return GameEntry(
                id = obj.getString("id"),
                name = obj.getString("name"),
                path = obj.getString("path"),
                desc = desc,
                image = if (obj.has("image") && !obj.isNull("image")) obj.getString("image") else "",
                releasedate = releasedate,
                developer = if (obj.has("developer") && !obj.isNull("developer")) obj.getString("developer") else "",
                publisher = if (obj.has("publisher") && !obj.isNull("publisher")) obj.getString("publisher") else "",
                genre = if (obj.has("genre") && !obj.isNull("genre")) obj.getString("genre") else "",
                players = if (obj.has("players") && !obj.isNull("players")) obj.getString("players") else "",
                hash = if (obj.has("hash") && !obj.isNull("hash")) obj.getString("hash") else "",
                rating = if (obj.has("rating") && !obj.isNull("rating")) obj.getString("rating") else ""
            )
        } catch (e: Exception) {
            Log.e(TAG, "Error parsing game entry: ${e.message}", e)
            return null
        }
    }
    
    /**
     * Parse un GamelistMetadata depuis JSONObject
     */
    private fun parseMetadata(obj: JSONObject, console: String): GamelistMetadata {
        val sourceDirs = mutableListOf<String>()
        val dirsArray = obj.optJSONArray("sourceDirectories")
        if (dirsArray != null) {
            for (i in 0 until dirsArray.length()) {
                try {
                    if (!dirsArray.isNull(i)) {
                        sourceDirs.add(dirsArray.getString(i))
                    }
                } catch (e: Exception) {
                    Log.w(TAG, "Error parsing sourceDirectory at index $i: ${e.message}")
                }
            }
        }
        
        return GamelistMetadata(
            generatedAt = obj.optLong("generatedAt", System.currentTimeMillis()),
            sourceDirectories = sourceDirs,
            autoGenerated = obj.optBoolean("autoGenerated", false),
            totalGames = obj.optInt("totalGames", 0),
            console = obj.optString("console", console)
        )
    }
    
    /**
     * Obtient les extensions par défaut pour une console
     * Utilise ConsoleNameMapper pour normaliser les noms alternatifs
     */
    fun getDefaultExtensions(consoleId: String): List<String> {
        // Normaliser avec ConsoleNameMapper (depuis Java)
        val canonicalId = com.retroplay.ConsoleNameMapper.normalizeToCanonical(consoleId)
        
        return when (canonicalId) {
            "nes" -> listOf(".nes", ".fds", ".unf", ".zip")
            "snes" -> listOf(".smc", ".sfc", ".fig", ".zip")
            "n64" -> listOf(".n64", ".z64", ".v64", ".zip")
            "gb" -> listOf(".gb", ".zip")
            "gbc" -> listOf(".gbc", ".zip")
            "gba" -> listOf(".gba", ".agb", ".zip")
            "genesis" -> listOf(".md", ".gen", ".smd", ".32x", ".zip")
            "megadrive" -> listOf(".md", ".gen", ".smd", ".32x", ".zip") // Alias pour genesis
            "mastersystem" -> listOf(".sms", ".zip")
            "gamegear" -> listOf(".gg", ".zip")
            "segacd" -> listOf(".iso", ".cue", ".bin", ".img", ".chd", ".gdi", ".zip")
            "psx" -> listOf(".iso", ".cue", ".bin", ".img", ".mdf", ".pbp", ".zip")
            "psp" -> listOf(".iso", ".cso", ".pbp", ".elf", ".zip")
            "atari2600" -> listOf(".a26", ".bin", ".zip")
            "atari5200" -> listOf(".a52", ".bin", ".zip")
            "atari7800" -> listOf(".a78", ".bin", ".zip", ".7z")
            "lynx" -> listOf(".lnx", ".zip")
            "ngp" -> listOf(".ngp", ".ngc", ".zip")
            "wonderswancolor" -> listOf(".ws", ".wsc", ".zip")
            "pce" -> listOf(".pce", ".sgx", ".zip")
            "fbneo" -> listOf(".zip", ".7z")
            "arcade" -> listOf(".zip", ".7z")
            "c64" -> listOf(".d64", ".d71", ".d81", ".t64", ".tap", ".prg", ".crt", ".bin", ".zip")
            "amiga" -> listOf(".adf", ".dsk", ".ipf", ".zip")
            "zxspectrum" -> listOf(".tap", ".tzx", ".z80", ".sna", ".dsk", ".trd", ".scl", ".zip")
            "spectrum" -> listOf(".tap", ".tzx", ".z80", ".sna", ".dsk", ".trd", ".scl", ".zip") // Alias
            else -> listOf(".zip", ".7z", ".rom", ".bin")
        }
    }
    
    /**
     * Fusionne deux gamelists (utile pour multi-répertoires)
     */
    fun mergeGamelists(gamelist1: Gamelist, gamelist2: Gamelist): Gamelist {
        val mergedGames = (gamelist1.games + gamelist2.games).distinctBy { it.path }
            .sortedBy { it.name.lowercase() }
        
        // Réassigner les IDs
        val reassignedGames = mergedGames.mapIndexed { index, game ->
            game.copy(id = (index + 1).toString())
        }
        
        val mergedMetadata = if (gamelist1.metadata != null && gamelist2.metadata != null) {
            GamelistMetadata(
                generatedAt = maxOf(gamelist1.metadata.generatedAt, gamelist2.metadata.generatedAt),
                sourceDirectories = (gamelist1.metadata.sourceDirectories + gamelist2.metadata.sourceDirectories).distinct(),
                autoGenerated = gamelist1.metadata.autoGenerated || gamelist2.metadata.autoGenerated,
                totalGames = reassignedGames.size,
                console = gamelist1.console
            )
        } else {
            null
        }
        
        return Gamelist(
            version = GAMELIST_VERSION,
            console = gamelist1.console,
            games = reassignedGames,
            metadata = mergedMetadata
        )
    }
    
    /**
     * Génère un gamelist.json au format JSON string (pour utilisation depuis Java)
     * Version simplifiée pour WebServer.java
     */
    @JvmStatic
    fun generateGamelistJsonString(consoleDir: File, consoleId: String): String {
        try {
            val gamelist = generateGamelist(consoleDir, consoleId)
            val jsonObj = org.json.JSONObject().apply {
                put("version", gamelist.version)
                put("console", gamelist.console)
                
                val gamesArray = org.json.JSONArray()
                gamelist.games.forEach { game ->
                    val gameObj = gameToJson(game)
                    gamesArray.put(gameObj)
                }
                put("games", gamesArray)
                
                // Ajouter metadata si disponible
                if (gamelist.metadata != null) {
                    val metadata = gamelist.metadata
                    val metadataObj = org.json.JSONObject().apply {
                        put("generatedAt", metadata.generatedAt)
                        put("autoGenerated", metadata.autoGenerated)
                        put("totalGames", metadata.totalGames)
                        put("console", metadata.console)
                        
                        val sourceDirsArray = org.json.JSONArray()
                        metadata.sourceDirectories.forEach { sourceDirsArray.put(it) }
                        put("sourceDirectories", sourceDirsArray)
                    }
                    put("metadata", metadataObj)
                }
            }
            
            return jsonObj.toString(2) // Indentation pour lisibilité
            
        } catch (e: Exception) {
            Log.e(TAG, "Error generating gamelist JSON string: ${e.message}", e)
            return "{\"games\":[]}" // Fallback
        }
    }
    
    /**
     * Ajoute seulement les nouvelles ROMs au gamelist.json existant
     * Ne modifie pas les ROMs existantes, ajoute seulement celles qui manquent
     * 
     * @param consoleDir Répertoire de la console
     * @param consoleId ID de la console
     * @return Nombre de nouvelles ROMs ajoutées
     */
    fun addNewRomsToGamelist(
        consoleDir: File,
        consoleId: String
    ): Int {
        try {
            val gamelistFile = File(consoleDir, "gamelist.json")
            
            // Charger le gamelist existant
            val existingGamelist = loadGamelist(consoleDir)
            if (existingGamelist == null) {
                Log.w(TAG, "No existing gamelist.json found for ${consoleDir.name}, skipping add new ROMs")
                return 0
            }
            
            // Créer un set des chemins existants pour vérification rapide (normalisés)
            val existingPaths = existingGamelist.games.map { 
                val path = it.path.replace("\\", "/")
                // Normaliser: enlever "./" au début
                if (path.startsWith("./")) path.substring(2) else path
            }.toSet()
            
            // Scanner le répertoire pour trouver de nouvelles ROMs (sans calculer hash pour les existantes)
            val canonicalId = com.retroplay.ConsoleNameMapper.normalizeToCanonical(consoleId)
            val extensions = getDefaultExtensions(canonicalId)
            val newGames = mutableListOf<GameEntry>()
            
            // Utiliser une version optimisée qui vérifie d'abord si le fichier existe
            scanDirectoryForNewRoms(consoleDir, canonicalId, extensions, newGames, consoleDir, existingPaths)
            
            if (newGames.isEmpty()) {
                Log.d(TAG, "No new ROMs found for ${consoleDir.name}")
                return 0
            }
            
            Log.i(TAG, "Found ${newGames.size} new ROMs for ${consoleDir.name}")
            
            // Ajouter les nouvelles ROMs à la liste existante
            val allGames = existingGamelist.games.toMutableList()
            val maxId = existingGamelist.games.maxOfOrNull { it.id.toIntOrNull() ?: 0 } ?: 0
            
            // Trier les nouvelles ROMs par nom et leur assigner des IDs
            val sortedNewGames = newGames.sortedBy { it.name.lowercase() }
            val newGamesWithIds = sortedNewGames.mapIndexed { index, game ->
                game.copy(id = (maxId + index + 1).toString())
            }
            
            allGames.addAll(newGamesWithIds)
            
            // Trier toutes les entrées par nom pour cohérence
            val sortedAllGames = allGames.sortedBy { it.name.lowercase() }
            val finalGamesWithIds = sortedAllGames.mapIndexed { index, game ->
                game.copy(id = (index + 1).toString())
            }
            
            // Sauvegarder le gamelist mis à jour
            val updatedGamelist = existingGamelist.copy(
                games = finalGamesWithIds,
                metadata = existingGamelist.metadata?.copy(
                    totalGames = finalGamesWithIds.size
                )
            )
            
            val success = saveGamelist(updatedGamelist, consoleDir)
            if (success) {
                Log.i(TAG, "Added ${newGames.size} new ROMs to gamelist for ${consoleDir.name}")
                return newGames.size
            } else {
                Log.e(TAG, "Failed to save updated gamelist for ${consoleDir.name}")
                return 0
            }
            
        } catch (e: Exception) {
            Log.e(TAG, "Error adding new ROMs to gamelist for ${consoleDir.name}: ${e.message}", e)
            return 0
        }
    }
    
    /**
     * Enrichit un gamelist.json existant avec les métadonnées scrappées en arrière-plan
     * Cette fonction est appelée après le scan initial pour ne pas ralentir le scan
     * 
     * @param consoleDir Répertoire de la console
     * @param consoleId ID de la console
     * @param onProgress Callback pour notifier la progression (optionnel)
     */
    fun enrichGamelistWithMetadata(
        consoleDir: File,
        consoleId: String,
        onProgress: ((current: Int, total: Int) -> Unit)? = null
    ) {
        CoroutineScope(Dispatchers.IO).launch {
            try {
                val gamelistFile = File(consoleDir, "gamelist.json")
                if (!gamelistFile.exists()) {
                    Log.w(TAG, "gamelist.json not found for ${consoleDir.name}, skipping enrichment")
                    return@launch
                }
                
                // Charger le gamelist existant
                val gamelist = loadGamelist(consoleDir)
                if (gamelist == null || gamelist.games.isEmpty()) {
                    Log.w(TAG, "Empty or invalid gamelist for ${consoleDir.name}, skipping enrichment")
                    return@launch
                }
                
                val normalizedConsoleId = com.retroplay.ConsoleNameMapper.normalizeToCanonical(consoleId)
                
                // Vérifier si la console est supportée par ScreenScraper AVANT de commencer
                if (!com.retroplay.scraper.ScraperManager.isConsoleSupported(normalizedConsoleId)) {
                    Log.d(TAG, "Console '$normalizedConsoleId' not supported by ScreenScraper, skipping enrichment")
                    return@launch
                }
                
                val totalGames = gamelist.games.size
                var enrichedCount = 0
                var needsSave = false
                
                Log.i(TAG, "Starting metadata enrichment for ${consoleDir.name} ($totalGames games)")
                
                // Enrichir chaque jeu SÉQUENTIELLEMENT (1 thread à la fois comme spécifié par ScreenScraper)
                // Utiliser une boucle for au lieu de mapIndexed pour garantir la sérialisation
                val enrichedGames = mutableListOf<GameEntry>()
                
                for ((index, game) in gamelist.games.withIndex()) {
                    onProgress?.invoke(index + 1, totalGames)
                    
                    // Si le jeu a déjà toutes les métadonnées, le garder tel quel
                    if (game.desc != null && game.genre != null && game.developer != null) {
                        enrichedGames.add(game)
                        continue
                    }
                    
                    // Si pas de hash, on ne peut pas scraper
                    if (game.hash == null || game.hash.isEmpty()) {
                        enrichedGames.add(game)
                        continue
                    }
                    
                    // Reconstruire le GameHash depuis le hash stocké
                    // Note: On ne peut pas reconstruire les 3 hashes, donc on utilise juste celui stocké
                    val gameHash = when {
                        game.hash.length == 40 -> com.retroplay.scraper.HashCalculator.GameHash(sha1 = game.hash)
                        game.hash.length == 32 -> com.retroplay.scraper.HashCalculator.GameHash(md5 = game.hash)
                        game.hash.length == 8 -> com.retroplay.scraper.HashCalculator.GameHash(crc32 = game.hash)
                        else -> {
                            Log.w(TAG, "Unknown hash format for ${game.name}: ${game.hash}")
                            enrichedGames.add(game)
                            continue
                        }
                    }
                    
                    // Scraper les métadonnées (SÉRIALISÉ - un seul appel à la fois)
                    // Le rate limiting dans ScraperManager garantit 12 secondes entre requêtes
                    val scrapedMetadata = com.retroplay.scraper.ScraperManager.scrapeGame(gameHash, normalizedConsoleId)
                    
                    if (scrapedMetadata != null) {
                        enrichedCount++
                        needsSave = true
                        
                        // Mettre à jour avec les métadonnées scrappées (garder les valeurs existantes si présentes)
                        enrichedGames.add(
                            game.copy(
                                name = scrapedMetadata.name.takeIf { it.isNotEmpty() } ?: game.name,
                                desc = game.desc ?: scrapedMetadata.description,
                                genre = game.genre ?: scrapedMetadata.genre,
                                releasedate = game.releasedate ?: scrapedMetadata.releaseDate,
                                developer = game.developer ?: scrapedMetadata.developer,
                                publisher = game.publisher ?: scrapedMetadata.publisher,
                                players = game.players ?: scrapedMetadata.players,
                                rating = game.rating ?: scrapedMetadata.rating
                            )
                        )
                    } else {
                        enrichedGames.add(game)
                    }
                }
                
                // Sauvegarder le gamelist enrichi si des modifications ont été faites
                if (needsSave) {
                    val enrichedGamelist = gamelist.copy(games = enrichedGames)
                    val success = saveGamelist(enrichedGamelist, consoleDir)
                    if (success) {
                        Log.i(TAG, "Enriched gamelist for ${consoleDir.name}: $enrichedCount/$totalGames games enriched")
                    } else {
                        Log.e(TAG, "Failed to save enriched gamelist for ${consoleDir.name}")
                    }
                } else {
                    Log.d(TAG, "No games needed enrichment for ${consoleDir.name}")
                }
                
            } catch (e: Exception) {
                Log.e(TAG, "Error enriching gamelist for ${consoleDir.name}: ${e.message}", e)
            }
        }
    }
}

