package com.retroplay.server;

import android.util.Log;
import com.retroplay.server.HtmlGenerator;
import java.io.*;
import java.io.File;

/**
 * Handler pour la gestion des fichiers GameLibrary-Data (ROMs, gamelists).
 * Extracted from WebServer to improve modularity and testability.
 * 
 * Gère:
 * - Service des fichiers depuis /storage/emulated/0/GameLibrary-Data/
 * - Auto-génération de gamelist.json si absent
 * - Streaming des gros fichiers (ROMs PSX/Sega CD 450+ MB)
 * - Listing des répertoires
 */
public class GameDataRequestHandler {

    private static final String TAG = "GameDataRequestHandler";
    private static final String GAMELIBRARY_DATA_BASE = "/storage/emulated/0/GameLibrary-Data/";

    /**
     * Sert un fichier depuis GameLibrary-Data
     * 
     * @param outputStream            Stream de sortie HTTP
     * @param path                    Chemin de la requête (ex:
     *                                "/gamedata/nes/gamelist.json")
     * @param method                  Méthode HTTP (GET, HEAD)
     * @param enableSharedArrayBuffer Si true, ajouter les headers COEP/COOP
     */
    public void serveGameDataFile(OutputStream outputStream, String path, String method,
            boolean enableSharedArrayBuffer) throws IOException {
        try {
            // Extraire le chemin du fichier (enlever /gamedata/)
            String filePath = path.substring(10); // Enlever "/gamedata/"

            // Décoder l'URL pour gérer les caractères spéciaux encodés (%2B → +, etc.)
            try {
                filePath = java.net.URLDecoder.decode(filePath, "UTF-8");
            } catch (Exception e) {
                Log.w(TAG, "Failed to decode URL: " + filePath);
            }

            // Cas spécial: auto-générer gamelist.json si demandé mais absent
            if (filePath.endsWith("/gamelist.json")) {
                // Extraire le chemin de la console (ex: "fbneo" ou "fbneo/sega")
                String consoleName = filePath.substring(0, filePath.lastIndexOf("/gamelist.json"));

                // CRITIQUE: Vérifier d'abord le chemin standard (roms/<console>/gamelist.json)
                String standardPath = com.retroplay.helpers.GameLibraryPaths.getGamelistPath(consoleName);
                File file = new File(standardPath);

                if (!file.exists()) {
                    // Check legacy path as fallback (in case user hasn't migrated)
                    String legacyPath = GAMELIBRARY_DATA_BASE + filePath;
                    File legacyFile = new File(legacyPath);
                    if (legacyFile.exists()) {
                        file = legacyFile;
                        Log.i(TAG, "Found legacy gamelist.json at: " + legacyPath);
                    }
                }

                if (!file.exists()) {
                    Log.i(TAG, "gamelist.json not found via /gamedata/, generating automatically for: " + consoleName);
                    // Vérifier si le répertoire console existe avant de générer
                    String consoleDirPath = GAMELIBRARY_DATA_BASE + consoleName;
                    File consoleDir = new File(consoleDirPath);
                    if (consoleDir.exists() && consoleDir.isDirectory()) {
                        serveAutoGeneratedGamelist(outputStream, consoleName, method);
                        return;
                    } else {
                        Log.w(TAG, "Console directory does not exist: " + consoleDirPath);
                        sendErrorResponse(outputStream, 404, "Console directory not found: " + consoleName);
                        return;
                    }
                }
            }

            // Construire le chemin complet vers GameLibrary-Data
            String fullPath = GAMELIBRARY_DATA_BASE + filePath;
            File file = new File(fullPath);

            if (!file.exists()) {
                Log.w(TAG, "File not found in GameLibrary-Data: " + fullPath);
                sendErrorResponse(outputStream, 404, "Not Found");
                return;
            }

            if (file.isDirectory()) {
                // Pour les répertoires, retourner un listing HTML simple
                serveDirectoryListing(outputStream, file, path);
                return;
            }

            // Déterminer le type de contenu
            String contentType = getContentType(filePath);

            // Envoyer la réponse HTTP avec headers SharedArrayBuffer conditionnels
            String response = "HTTP/1.1 200 OK\r\n" +
                    "Content-Type: " + contentType + "\r\n" +
                    "Content-Length: " + file.length() + "\r\n" +
                    "Access-Control-Allow-Origin: *\r\n" +
                    getSharedArrayBufferHeaders(enableSharedArrayBuffer) +
                    "\r\n";

            outputStream.write(response.getBytes());

            // Pour les requêtes HEAD, ne pas envoyer le contenu
            if (!"HEAD".equals(method)) {
                // Streaming avec buffer 64KB pour les gros fichiers (ROMs PSX/Sega CD 450+ MB)
                FileInputStream fileInputStream = new FileInputStream(file);
                byte[] buffer = new byte[65536]; // 64KB buffer pour performance
                int bytesRead;

                while ((bytesRead = fileInputStream.read(buffer)) != -1) {
                    outputStream.write(buffer, 0, bytesRead);
                }

                fileInputStream.close();
            }
            outputStream.flush();

            Log.d(TAG, "Served GameLibrary-Data file: " + fullPath);

        } catch (IOException e) {
            Log.e(TAG, "Error serving GameLibrary-Data file: " + path, e);
            sendErrorResponse(outputStream, 500, "Internal Server Error");
        }
    }

    /**
     * Génère automatiquement un gamelist.json à partir des ROMs du répertoire
     */
    private void serveAutoGeneratedGamelist(OutputStream outputStream, String consoleName, String method)
            throws IOException {
        try {
            String consolePath = GAMELIBRARY_DATA_BASE + consoleName;
            File consoleDir = new File(consolePath);

            Log.d(TAG, "serveAutoGeneratedGamelist: consoleName=" + consoleName + ", path=" + consolePath);
            Log.d(TAG, "Directory exists: " + consoleDir.exists() + ", isDirectory: "
                    + (consoleDir.exists() ? consoleDir.isDirectory() : "N/A"));

            if (!consoleDir.exists() || !consoleDir.isDirectory()) {
                // Si le répertoire n'existe pas avec ce nom, essayer de trouver un alias
                // Ex: "genesis" n'existe pas mais "megadrive" existe
                String normalizedId = com.retroplay.ConsoleNameMapper.normalizeToCanonical(consoleName);
                if (!normalizedId.equals(consoleName)) {
                    // Essayer de trouver le répertoire réel en cherchant dans GameLibrary-Data
                    File gamelibraryDir = new File(GAMELIBRARY_DATA_BASE);
                    if (gamelibraryDir.exists() && gamelibraryDir.isDirectory()) {
                        File[] dirs = gamelibraryDir.listFiles(File::isDirectory);
                        if (dirs != null) {
                            for (File dir : dirs) {
                                String dirName = dir.getName();
                                String dirNormalized = com.retroplay.ConsoleNameMapper.normalizeToCanonical(dirName);
                                if (dirNormalized.equals(normalizedId)) {
                                    consoleDir = dir;
                                    consoleName = dirName; // Utiliser le nom réel du répertoire
                                    Log.i(TAG, "Found console directory by alias: " + dirName + " (for " + consoleName
                                            + " -> " + normalizedId + ")");
                                    break;
                                }
                            }
                        }
                    }
                }

                if (!consoleDir.exists() || !consoleDir.isDirectory()) {
                    Log.e(TAG, "Console directory not found: " + consolePath);
                    sendErrorResponse(outputStream, 404, "Console directory not found: " + consoleName);
                    return;
                }
            }

            // Utiliser GamelistManager amélioré (Kotlin)
            // Note: @JvmStatic permet d'appeler directement depuis Java
            Log.d(TAG, "Calling GamelistManager.generateGamelistJsonString for: " + consoleName);
            String jsonContent = com.retroplay.GamelistManager.generateGamelistJsonString(consoleDir, consoleName);

            if (jsonContent == null || jsonContent.isEmpty()) {
                Log.e(TAG, "GamelistManager returned empty content for: " + consoleName);
                sendErrorResponse(outputStream, 500, "Failed to generate gamelist");
                return;
            }

            // Calculer Content-Length en bytes (UTF-8)
            byte[] jsonBytes = jsonContent.getBytes("UTF-8");
            String response = "HTTP/1.1 200 OK\r\n" +
                    "Content-Type: application/json; charset=utf-8\r\n" +
                    "Content-Length: " + jsonBytes.length + "\r\n" +
                    "Access-Control-Allow-Origin: *\r\n" +
                    "Access-Control-Allow-Methods: GET, POST, OPTIONS\r\n" +
                    "Access-Control-Allow-Headers: Content-Type\r\n" +
                    "\r\n";

            outputStream.write(response.getBytes());

            if (!"HEAD".equals(method)) {
                outputStream.write(jsonBytes);
            }
            outputStream.flush();

            // Compter les jeux pour le log
            try {
                org.json.JSONObject jsonObj = new org.json.JSONObject(jsonContent);
                org.json.JSONArray gamesArray = jsonObj.getJSONArray("games");
                Log.i(TAG, "Served improved auto-generated gamelist.json for " + consoleName + " with "
                        + gamesArray.length() + " games (with CRC32, size, metadata)");
            } catch (Exception e) {
                Log.i(TAG, "Served improved auto-generated gamelist.json for " + consoleName);
            }

        } catch (Exception e) {
            Log.e(TAG, "Error generating improved gamelist.json", e);
            sendErrorResponse(outputStream, 500, "Internal Server Error");
        }
    }

    /**
     * Sert un listing simple d'un répertoire (pour le scanner AUTO SCAN)
     */
    private void serveDirectoryListing(OutputStream outputStream, File directory, String path) throws IOException {
        String htmlContent = HtmlGenerator.generateSimpleDirectoryListing(directory, path);

        String response = "HTTP/1.1 200 OK\r\n" +
                "Content-Type: text/html; charset=UTF-8\r\n" +
                "Content-Length: " + htmlContent.getBytes("UTF-8").length + "\r\n" +
                "Access-Control-Allow-Origin: *\r\n" +
                "Access-Control-Allow-Methods: GET, POST, OPTIONS\r\n" +
                "Access-Control-Allow-Headers: Content-Type\r\n" +
                "\r\n";

        outputStream.write(response.getBytes("UTF-8"));
        outputStream.write(htmlContent.getBytes("UTF-8"));
        outputStream.flush();

        Log.d(TAG, "Served directory listing: " + path);
    }

    /**
     * Obtient le type de contenu MIME pour un fichier
     */
    private String getContentType(String filePath) {
        String lowerPath = filePath.toLowerCase();
        if (lowerPath.endsWith(".json")) {
            return "application/json; charset=utf-8";
        } else if (lowerPath.endsWith(".zip")) {
            return "application/zip";
        } else if (lowerPath.endsWith(".bin") || lowerPath.endsWith(".rom")) {
            return "application/octet-stream";
        } else if (lowerPath.endsWith(".iso") || lowerPath.endsWith(".img")) {
            return "application/x-iso9660-image";
        } else if (lowerPath.endsWith(".cue")) {
            return "application/x-cue";
        } else if (lowerPath.endsWith(".chd")) {
            return "application/x-chd";
        } else {
            return "application/octet-stream";
        }
    }

    /**
     * Génère les headers SharedArrayBuffer si nécessaire
     */
    private String getSharedArrayBufferHeaders(boolean enable) {
        if (enable) {
            return "Cross-Origin-Embedder-Policy: require-corp\r\n" +
                    "Cross-Origin-Opener-Policy: same-origin\r\n";
        }
        return "";
    }

    /**
     * Envoie une réponse d'erreur HTTP
     */
    private void sendErrorResponse(OutputStream outputStream, int statusCode, String message) throws IOException {
        String response = "HTTP/1.1 " + statusCode + " " + message + "\r\n" +
                "Content-Type: text/plain\r\n" +
                "Content-Length: " + message.length() + "\r\n" +
                "\r\n" +
                message;
        outputStream.write(response.getBytes());
        outputStream.flush();
    }
}
